#
#
ChatBoxWidthInPixels: 320

#
# Number of lines to be displayed, including PageHeader and PageFooter
ChatBoxHeightInLines: 10

eithon:
  UseMarkUpForMessages: 1
  UseWrappingForMessages: 1
  
  #
  # Debug level
  #  0 = NONE (no debug messages)
  #  1 = MAJOR (only major messages)
  #  2 = MINOR (also minor messages)
  #  3 = VERBOSE (all messages)
  #
  EithonDebugLevel: 3

messages:
  #
  # The following two messages have the following possible parameters
  # %TITLE%: The name of the document that is displayed, with uppercase first character.
  # Example: The document "help.txt" will have %TITLE% = "Help"
  # %CURRENT_PAGE%: The current page. 1 for the first page, 2 for the second, etc.
  # %TOTAL_PAGES%: The total number of pages, i.e. when we are at the last page, the %CURRENT_PAGE% will be the same as %TOTAL_PAGES%
  PageHeader: "	*[ [color=aqua]%TITLE% [/color]]"
  PageFooter: ' *[Page [color=aqua]%CURRENT_PAGE%[/color] of [color=aqua]%TOTAL_PAGES%[/color]]'
