#
#
DoDebugPrint: 0

#
#
ChatBoxWidthInPixels: 320

#
# 0 = display message below
# 1 = display message above
#
DisplayPageOfMessageAbove: 0

messages:

  #
  # PageOfMessage has 2 parameters: <current page> (%d), <total pages> (%d)
  PageOf: Page %d of %d

