name: EithonDocs
main: se.fredsfursten.eithondocs.EithonDocsPlugin
version: 1.3
author: vanbrayne
description: A Minecraft plugin for rules, etc
commands:
  edocs:
    description: Documentation
    usage: /edocs rules | reload | help
    permission-message: You don't have <permission>
permissions:
  edocs.*:
    description: Gives access to all eithondocs commands
    default: op
    edocs.rules: true
    edocs.reload: true
    edocs.help: true
  edocs.rules:
    description: Access to /edocs rules command
    default: op
  edocs.reload:
    description: Access to /edocs reload command
    default: op
  edocs.help:
    description: Access to /edocs help command
    default: op
