name: EithonDocs
main: net.eithon.plugin.eithondocs.Plugin
version: 2.1
author: vanbrayne
description: A Minecraft plugin for rules, etc
depend: [EithonLibrary]
commands:
  edocs:
    description: Documentation
    usage: /edocs reload | <file name>
    permission-message: You don't have <permission>
permissions:
  edocs.*:
    description: Gives access to all eithondocs commands
    default: op
    edocs.read: true
    edocs.reload: true
  edocs.rules:
    description: Access to /edocs rules command
    default: op
  edocs.read:
    description: Can read documents
    default: op
