name: EithonDocs
main: net.eithon.plugin.docs.Plugin
version: 2.4
author: vanbrayne
description: A Minecraft plugin for rules, etc
depend: [EithonLibrary]
commands:
  edocs:
    description: Documentation
    usage: /edocs reload | <file name>
    permission-message: You don't have <permission>
permissions:
  edocs.*:
    description: Gives access to all eithondocs commands
    default: op
    edocs.read: true
    edocs.reload: true
  edocs.reload:
    description: Access to /edocs reload command
    default: op
  edocs.read:
    description: Can read documents
    default: op
